name: PHP Composer

on:
  push:
    branches: [ "dd", "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./php

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: composer install
        run: composer install

      - name: phpunit
        run: php vendor/bin/phpunit